# FROM openjdk:17-jdk-alpine
FROM openjdk:17-oracle
LABEL Rafael Martinez Murga <rafael.martinez@cevisur.com.mx>
# a default value
ENV MONGO_HOSTNAME mongodb+srv://rafael.martinez:blackburzum6B@cluster0.rd0rzqg.mongodb.net/unam
ENV MONGO_DB unam
ENV MONGO_USER rafael.martinez
ENV MONGO_PWD blackburzum6B
ENV TOMCAT_PORT 8080
EXPOSE 8080
ARG JAR_FILE=target/*.jar
COPY target/*.jar app.jar
CMD ["java", "-jar", "/app.jar"]